Repository Neogasogaeseo/Naega-Server, pull requests merged in 2022-03, with the labels that each got.

#112 [refactor] 팀소서 이슈 조회 리스폰스 수정
  functions/api/routes/team/teamDetailIssueGET.js
  functions/api/routes/team/teamDetailMyIssueGET.js
  functions/api/routes/team/teamIssueGET.js
  functions/db/issueDB.js
  functions/package-lock.json
Labels: refactor 🪐, get :egg:, 팀소서 메인 :busts_in_silhouette:, 팀 디테일 페이지 :bento:

#114 [refactor] 마이페이지 조회 리스폰스 수정
  functions/api/routes/user/userPinnedTeamGET.js
  functions/constants/responseMessage.js
  functions/db/teamDB.js
Labels: refactor 🪐

#117 [chore] 팀 정보 조회 리스폰스 수정
  functions/db/teamDB.js
Labels: get :egg:, 팀 디테일 페이지 :bento:, chore :zap:

#120 [refactor] 폴더링
  functions/api/routes/auth/authLoginPOST.js
  functions/api/routes/auth/authRegisterPOST.js
  functions/api/routes/form/formAnswerCreatePOST.js
  functions/api/routes/form/formAnswerGET.js
  functions/api/routes/form/formBannerGET.js
  functions/api/routes/form/formCreateGET.js
  functions/api/routes/form/formCreatePOST.js
  functions/api/routes/form/formDetailAnswerGET.js
  functions/api/routes/form/formDetailAnswerPinPUT.js
  functions/api/routes/form/formDetailGET.js
  functions/api/routes/form/formMyGET.js
  functions/api/routes/form/formMyMostGET.js
  functions/api/routes/form/formMyNewGET.js
  functions/api/routes/form/formTemplatePopularGET.js
  functions/api/routes/form/formTemplateRecentGET.js
  functions/api/routes/team/teamDetailGET.js
  functions/api/routes/team/teamDetailIssueGET.js
  functions/api/routes/team/teamDetailMyIssueGET.js
  functions/api/routes/team/teamFeedbackCreatePOST.js
  functions/api/routes/team/teamGET.js
  functions/api/routes/team/teamInviteAcceptPUT.js
  functions/api/routes/team/teamInviteGET.js
  functions/api/routes/team/teamInviteRejectPUT.js
  functions/api/routes/team/teamIssueCategoryGET.js
  functions/api/routes/team/teamIssueDetailFeedbackGET.js
  functions/api/routes/team/teamIssueDetailFeedbackPinPUT.js
  functions/api/routes/team/teamIssueDetailGET.js
  functions/api/routes/team/teamIssueGET.js
  functions/api/routes/team/teamIssuePOST.js
  functions/api/routes/team/teamMemberListGET.js
  functions/api/routes/team/teamPOST.js
  functions/api/routes/team/teamPUT.js
  functions/api/routes/user/keywordCreatePOST.js
  functions/api/routes/user/keywordListGET.js
  functions/api/routes/user/userInformationByProfileIdGET.js
  functions/api/routes/user/userInformationByTokenGET.js
  functions/api/routes/user/userPinnedAnswerGET.js
  functions/api/routes/user/userPinnedTeamGET.js
  functions/api/routes/user/userSearchGET.js
  functions/lib/crypto.js
  functions/lib/resizeImage.js
  functions/lib/slackAPI.js
Labels: refactor 🪐

#121 [chore] 기획 변동사항
  functions/db/teamDB.js
Labels: get :egg:, 팀 디테일 페이지 :bento:, chore :zap:

#125 [feat] 팀소서 미트볼
  functions/api/routes/team/index.js
  functions/api/routes/team/teamDELETE.js
  functions/api/routes/team/teamHostPUT.js
  functions/api/routes/team/teamMemberDELETE.js
  functions/constants/responseMessage.js
  functions/db/memberDB.js
  functions/db/teamDB.js
Labels: feature 🎄, put :sparkles:, 팀소서 미트볼 :meat_on_bone:, delete :dagger:

#122 [chore] light_icon_image 컬럼 삭제로 인한 변수명 변경
  functions/api/routes/form/formCreatePOST.js
  functions/db/answerDB.js
  functions/db/formDB.js
Labels: get :egg:, chore :zap:, 마이페이지 :face_in_clouds:, 너소서 메인 :+1:

#129 [feat] 알림
  firebase.json
  functions/api/routes/user/index.js
  functions/api/routes/user/userNoticeBarGET.js
  functions/api/routes/user/userNoticeListGET.js
  functions/constants/responseMessage.js
  functions/db/memberDB.js
  functions/db/teamDB.js
Labels: feature 🎄, get :egg:, 알림 :alarm_clock:

#131 [feat] 팀 정보 수정
  functions/api/routes/team/index.js
  functions/api/routes/team/teamEditGET.js
  functions/api/routes/team/teamEditPUT.js
Labels: feature 🎄, get :egg:, 팀 생성/수정 :stuck_out_tongue_winking_eye:, put :sparkles:
