Repository Neogasogaeseo/Naega-Server, pull requests merged in 2022-08, with the labels that each got.

#202 [fix] QA
  functions/api/routes/team/teamMemberEditPOST.js
  functions/db/linkAnswerKeywordDB.js
  functions/db/memberDB.js
  functions/db/userDB.js
Labels: fix ☔️, chore :zap:

#203 [fix] QA
  functions/api/index.js
  functions/db/linkFeedbacKeywordDB.js
Labels: fix ☔️

#208 [feature] 삭제 시 하위 테이블 삭제 처리
  functions/api/routes/team/teamDELETE.js
  functions/api/routes/team/teamHostPUT.js
  functions/api/routes/team/teamMemberDELETE.js
  functions/db/feedbackDB.js
  functions/db/issueDB.js
  functions/db/keywordDB.js
  functions/db/linkFeedbacKeywordDB.js
  functions/db/memberDB.js
Labels: add :heavy_plus_sign:, 팀소서 미트볼 :meat_on_bone:
