Repository Neogasogaeseo/Naega-Server, pull requests merged in 2022-06, with the labels that each got.

#193 [fix] QA
  functions/api/routes/form/formTemplateGET.js
  functions/api/routes/form/index.js
  functions/api/routes/team/teamIssueGET.js
  functions/constants/responseMessage.js
  functions/db/formDB.js
  functions/db/issueDB.js
  functions/db/memberDB.js
Labels: fix ☔️

#194 [fix] 쿼리문 팀장 여부 select 추가
  functions/db/memberDB.js
Labels: fix ☔️, get :egg:

#196 [fix] QA
  functions/api/routes/user/userNoticeListGET.js
  functions/db/memberDB.js
Labels: chore :zap:, add :heavy_plus_sign:

#197 [fix] QA
  functions/api/routes/team/teamMemberEditPOST.js
  functions/api/routes/team/teamPOST.js
  functions/api/routes/user/userInformationByProfileIdGET.js
  functions/db/keywordDB.js
  functions/db/memberDB.js
  functions/db/userDB.js
Labels: fix ☔️, chore :zap:
